import 'package:json_annotation/json_annotation.dart';
import '../utils/constants.dart';

part 'assessment_model.g.dart';

/// Assessment model representing a running talent assessment
@JsonSerializable()
class AssessmentModel {
  final String id;
  final String userId;
  final DateTime createdAt;
  final AssessmentStatus status;
  final String? videoUrl;
  final RunningMetrics? metrics;
  final TalentScore? score;
  final String? feedback;
  final Map<String, dynamic>? metadata;

  const AssessmentModel({
    required this.id,
    required this.userId,
    required this.createdAt,
    required this.status,
    this.videoUrl,
    this.metrics,
    this.score,
    this.feedback,
    this.metadata,
  });

  factory AssessmentModel.fromJson(Map<String, dynamic> json) =>
      _$AssessmentModelFromJson(json);

  Map<String, dynamic> toJson() => _$AssessmentModelToJson(this);

  AssessmentModel copyWith({
    String? id,
    String? userId,
    DateTime? createdAt,
    AssessmentStatus? status,
    String? videoUrl,
    RunningMetrics? metrics,
    TalentScore? score,
    String? feedback,
    Map<String, dynamic>? metadata,
  }) {
    return AssessmentModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      createdAt: createdAt ?? this.createdAt,
      status: status ?? this.status,
      videoUrl: videoUrl ?? this.videoUrl,
      metrics: metrics ?? this.metrics,
      score: score ?? this.score,
      feedback: feedback ?? this.feedback,
      metadata: metadata ?? this.metadata,
    );
  }
}

/// Running metrics extracted from pose analysis
@JsonSerializable()
class RunningMetrics {
  final double cadence; // steps per minute
  final double strideLength; // in meters
  final double groundContactTime; // in milliseconds
  final double verticalOscillation; // in cm
  final double footStrikePattern; // heel/mid/forefoot strike ratio
  final double armSwingAngle; // in degrees
  final double bodyLean; // in degrees
  final double symmetryScore; // 0-1 scale
  final List<PoseKeypoint> keypoints;

  const RunningMetrics({
    required this.cadence,
    required this.strideLength,
    required this.groundContactTime,
    required this.verticalOscillation,
    required this.footStrikePattern,
    required this.armSwingAngle,
    required this.bodyLean,
    required this.symmetryScore,
    required this.keypoints,
  });

  factory RunningMetrics.fromJson(Map<String, dynamic> json) =>
      _$RunningMetricsFromJson(json);

  Map<String, dynamic> toJson() => _$RunningMetricsToJson(this);
}

/// Individual pose keypoint
@JsonSerializable()
class PoseKeypoint {
  final String name;
  final double x;
  final double y;
  final double confidence;
  final int timestamp; // in milliseconds

  const PoseKeypoint({
    required this.name,
    required this.x,
    required this.y,
    required this.confidence,
    required this.timestamp,
  });

  factory PoseKeypoint.fromJson(Map<String, dynamic> json) =>
      _$PoseKeypointFromJson(json);

  Map<String, dynamic> toJson() => _$PoseKeypointToJson(this);
}

/// Talent score generated by AI analysis
@JsonSerializable()
class TalentScore {
  final double overallScore; // 0-100 scale
  final Map<String, double> categoryScores; // efficiency, form, potential, etc.
  final ResultQuality quality;
  final List<String> strengths;
  final List<String> improvementAreas;
  final String recommendation;

  const TalentScore({
    required this.overallScore,
    required this.categoryScores,
    required this.quality,
    required this.strengths,
    required this.improvementAreas,
    required this.recommendation,
  });

  factory TalentScore.fromJson(Map<String, dynamic> json) =>
      _$TalentScoreFromJson(json);

  Map<String, dynamic> toJson() => _$TalentScoreToJson(this);
}

/// Video recording session data
@JsonSerializable()
class RecordingSession {
  final String id;
  final DateTime startTime;
  final DateTime? endTime;
  final int duration; // in milliseconds
  final String? localPath;
  final RecordingQuality quality;
  final Map<String, dynamic>? settings;

  const RecordingSession({
    required this.id,
    required this.startTime,
    this.endTime,
    required this.duration,
    this.localPath,
    required this.quality,
    this.settings,
  });

  factory RecordingSession.fromJson(Map<String, dynamic> json) =>
      _$RecordingSessionFromJson(json);

  Map<String, dynamic> toJson() => _$RecordingSessionToJson(this);
}

/// Video recording quality settings
enum RecordingQuality {
  low,    // 480p
  medium, // 720p
  high,   // 1080p
  ultra,  // 4K
}

extension RecordingQualityExtension on RecordingQuality {
  String get displayName {
    switch (this) {
      case RecordingQuality.low:
        return '480p';
      case RecordingQuality.medium:
        return '720p';
      case RecordingQuality.high:
        return '1080p';
      case RecordingQuality.ultra:
        return '4K';
    }
  }
}